In [2]:
import numpy as np

1. 创建 1×5 全 0 浮点向量

In [7]:
a = np.zeros(5, dtype=float)
a

array([0., 0., 0., 0., 0.])

2. 创建 3×3 单位阵(对角线为1)

In [8]:
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

3. 生成 0–9 的数组  

In [10]:
my_list = range(0, 10)
my_list

range(0, 10)

4. 从 0 到 1 等间隔 5 个数  

In [12]:
my_list = np.linspace(0,1,5)
my_list

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

5. 随机 2×3 正态分布  

In [14]:
a = np.random.randn(2, 3)
a

array([[-0.62122007,  0.5105913 , -0.1832004 ],
       [-0.38875061, -0.86727411, -1.1598184 ]])

6. 将 1~6 变成 2×3 数组  

In [15]:
a = np.arange(1, 7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

7. 获取第 2 行整行  

In [19]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a = a[1, :]
a

array([4, 5, 6])

8. 获取第 1 列整列  

In [20]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a = a[:, 0]
a

array([1, 4])

9. 取前两行、后两列  

In [21]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a = a[:2, -2:]
a

array([[2, 3],
       [5, 6]])

10. 倒序整个数组

In [3]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a = a[::-1, ::-1]
a

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

11. 行倒序，列不变

In [4]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a = a[::-1, :]
a

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

12. 把 3×4 数组展平成一维

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [17, 18, 19]])
a = a.reshape(1,12)
a

# 此时a变成了只有一行数据的二维向量，不满足题意

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 17, 18, 19]])

In [ ]:
#可以做如下修改
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [17, 18, 19]])
x = b.ravel()      # 推荐，返回视图
y = b.flatten()    # 返回拷贝
z = b.reshape(-1)  # 显式变成一维

14. 计算 a 的转置

In [4]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [17, 18, 19]])
a = b.T
a

array([[ 1,  4,  7, 17],
       [ 2,  5,  8, 18],
       [ 3,  6,  9, 19]])

15. 将 a 与 a.T 做矩阵乘

In [5]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [17, 18, 19]])
a = b @ b.T
a

array([[ 14,  32,  50, 110],
       [ 32,  77, 122, 272],
       [ 50, 122, 194, 434],
       [110, 272, 434, 974]])

16. 逐元素平方

In [6]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [17, 18, 19]])
a = b ** 2
a

array([[  1,   4,   9],
       [ 16,  25,  36],
       [ 49,  64,  81],
       [289, 324, 361]])

17. 所有元素加 1

In [7]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [17, 18, 19]])
a = b + 2
a

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [19, 20, 21]])

18. 求每行最大值

In [8]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [17, 18, 19]])
a = b.max(axis=1)
a

array([ 3,  6,  9, 19])

19. 求每列平均值

In [11]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [17, 18, 19]])
a = b.mean(axis=0)
a

array([7.25, 8.25, 9.25])

20. 计算总和

In [13]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [17, 18, 19]])
a = b.sum()
a

np.int64(99)

21. 计算累积和（flatten 后）

In [19]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [17, 18, 19]])
c = b.flatten()
c
a = c.cumsum()
a

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 62, 80, 99])

22. 找到大于 3 的索引

In [21]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [17, 18, 19]])
a = np.where(b > 3)
a

(array([1, 1, 1, 2, 2, 2, 3, 3, 3]), array([0, 1, 2, 0, 1, 2, 0, 1, 2]))

23. 布尔掩码过滤

In [25]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [17, 18, 19]])
a = b[b > 3]
a

array([ 4,  5,  6,  7,  8,  9, 17, 18, 19])

24. 排序每行

In [26]:
b = np.array([[1, 5, 3], [8, 5, 6], [5, 10, 9], [100, 18, 19]])
np.sort(b, axis=1)

array([[  1,   3,   5],
       [  5,   6,   8],
       [  5,   9,  10],
       [ 18,  19, 100]])

25. 去重 1-D 数组

In [30]:
b = np.array([1, 2, 3, 4, 3])
c = np.unique_values(b)
c

array([1, 2, 3, 4])

26. 交换第 1、2 行

In [31]:
b = np.array([[1, 5, 3], [8, 5, 6], [5, 10, 9], [100, 18, 19]])
b[[0, 1]] = b[[1, 0]]
b

array([[  8,   5,   6],
       [  1,   5,   3],
       [  5,  10,   9],
       [100,  18,  19]])

27. 交换第 0、2 列

In [34]:
b = np.array([[1, 5, 3], [8, 5, 6], [5, 10, 9], [100, 18, 19]])
b[:, [0, 2]] = b[:, [2, 0]]
b

array([[  3,   5,   1],
       [  6,   5,   8],
       [  9,  10,   5],
       [ 19,  18, 100]])

28. 在第 1 行位置插入一行 0

In [35]:
b = np.array([[1, 5, 3], [8, 5, 6], [5, 10, 9], [100, 18, 19]])
np.insert(b, 1, 0, axis=0)

array([[  1,   5,   3],
       [  0,   0,   0],
       [  8,   5,   6],
       [  5,  10,   9],
       [100,  18,  19]])

29. 删除第 2 列

In [ ]:
b = np.array([[1, 5, 3], [8, 5, 6], [5, 10, 9], [100, 18, 19]])
np.delete(b, 1, axis=1)

array([[  1,   5],
       [  8,   5],
       [  5,  10],
       [100,  18]])

30. 沿行拼接两个 2×3 数组

In [3]:
a = np.array([[1, 5, 3], [8, 5, 6]])
b = np.array([[5, 10, 9], [100, 18, 19]])

c = np.vstack([a,b])
c


array([[  1,   5,   3],
       [  8,   5,   6],
       [  5,  10,   9],
       [100,  18,  19]])

31. 沿列拼接

In [5]:
a = np.array([[1, 5, 3], [8, 5, 6]])
b = np.array([[5, 10, 9], [100, 18, 19]])
c = np.hstack([a, b])
c

array([[  1,   5,   3,   5,  10,   9],
       [  8,   5,   6, 100,  18,  19]])

32. 水平拆分成 3 份

In [6]:
b = np.array([[5, 10, 9], [100, 18, 19]])
a = np.hsplit(b, 3)
a

[array([[  5],
        [100]]),
 array([[10],
        [18]]),
 array([[ 9],
        [19]])]

33. 垂直拆分成 2 份

In [7]:
b = np.array([[5, 10, 9], [100, 18, 19]])
a = np.vsplit(b, 2)
a

[array([[ 5, 10,  9]]), array([[100,  18,  19]])]

34. 广播：3×1 + 1×3 → 3×3

In [9]:
c = np.arange(3).reshape(3, 1)
d = np.arange(3).reshape(1, 3)
print(c)
print(d)
c + d

[[0]
 [1]
 [2]]
[[0 1 2]]


array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

35. 广播：5×1×4 + 3×4 → 5×3×4

In [15]:
c = np.arange(20).reshape(5, 1, 4)
d = np.arange(12).reshape(3, 4)
print(c)
print(d)
print("="*10)
a  = c + d
print(a)
print(a.shape)

[[[ 0  1  2  3]]

 [[ 4  5  6  7]]

 [[ 8  9 10 11]]

 [[12 13 14 15]]

 [[16 17 18 19]]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  2  4  6]
  [ 4  6  8 10]
  [ 8 10 12 14]]

 [[ 4  6  8 10]
  [ 8 10 12 14]
  [12 14 16 18]]

 [[ 8 10 12 14]
  [12 14 16 18]
  [16 18 20 22]]

 [[12 14 16 18]
  [16 18 20 22]
  [20 22 24 26]]

 [[16 18 20 22]
  [20 22 24 26]
  [24 26 28 30]]]
(5, 3, 4)


36. 使用 einsum 计算矩阵乘法

In [16]:
c = np.arange(6).reshape(3, 2)
d = np.arange(8).reshape(2, 4)

a = np.einsum('ij,jk->ik', c, d)
a

array([[ 4,  5,  6,  7],
       [12, 17, 22, 27],
       [20, 29, 38, 47]])

37. 使用 einsum 求每行和

In [18]:
c = np.arange(6).reshape(3, 2)
a = np.einsum('ij->i', c)
a

array([1, 5, 9])

38. 使用 einsum 求每列和

In [19]:
c = np.arange(6).reshape(3, 2)
a = np.einsum('ij->j', c)
a

array([6, 9])

39. 使用 einsum 求迹（对角线之和）

In [22]:
c = np.arange(16).reshape(4, 4)
a = np.einsum('ii->', c)
a

np.int64(30)

40. 使用 einsum 计算外积

In [23]:
u = np.array([1, 2])
v = np.array([3, 4, 5])
np.einsum('i,j->ij', u, v)

array([[ 3,  4,  5],
       [ 6,  8, 10]])

41. 使用 einsum 计算内积

In [24]:
np.einsum('i,i->', u, u)

np.int64(5)

42. 计算 3×3×3 张量沿 axis=1 的 sum

In [25]:
t = np.ones((3, 3, 3))
np.einsum('ijk->ik', t)

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

43. 使用 einsum 做批量矩阵乘 (batch×n×n)

In [28]:
batch = np.random.randn(10, 4, 4)
print(batch)
print('=='*10)
result = np.einsum('bij,bjk->bik', batch, batch)
print(result)

[[[ 0.19451858  1.87895653 -0.32939439 -0.68656169]
  [ 1.91170913 -0.02004727 -1.1980882   0.57849521]
  [ 1.2655844   0.44679616  1.20452613  0.03659526]
  [-0.87553401 -0.427904    1.13263545 -0.85191512]]

 [[-0.03430467 -0.29691512 -2.0485871   0.00931297]
  [-1.04357624  0.71499629 -0.61038261  0.86258688]
  [ 0.87652028 -1.17662259 -1.88212754  0.53226739]
  [-0.10524392  1.45701361 -1.5869933  -0.11914485]]

 [[-0.91456402  0.9267777   1.05225666  1.09205032]
  [-0.60031473  0.93790514  0.0641807  -0.36063464]
  [ 0.68893933 -0.55796622 -1.40796107 -1.89022835]
  [ 1.26227696  0.52957307  1.0118599  -0.14097094]]

 [[ 1.11027815  0.66984412 -0.55698845 -0.58036758]
  [ 1.60454759  0.37087039  0.63201026 -0.26642716]
  [-0.57762109 -2.11106415 -0.59080245 -0.13829763]
  [ 1.594618   -1.10901243 -0.73434163  0.49889077]]

 [[-1.24277165 -1.66142421  0.55391684  0.21490827]
  [-0.26320547 -0.21538815  0.48316953  0.9484791 ]
  [ 1.1607425   1.40724109 -0.98238631  1.7626049 ]
  [ 

44. 设置打印精度 2 位小数

In [ ]:
# 全局设置 NumPy 打印时的浮点精度（小数点后保留 2 位）
np.set_printoptions(precision=2)

a = np.array([3.1415926, 2.71828, 1.618])
print(a) 

[3.14 2.72 1.62]


45. 关闭科学计数法

In [ ]:
np.set_printoptions(suppress=True)

46. 保存数组到磁盘并读取

In [ ]:
np.save('a.npy', a)
aa = np.load('a.npy')

47. 保存为文本并读取

In [ ]:
np.savetxt('a.txt', a, fmt='%d')
bb = np.loadtxt('a.txt', dtype=int)

48. 统计描述（min, max, mean, std） 

In [ ]:
a = np.arange(12).reshape(4, 3)
np.array([a.min(), a.max(), a.mean(), a.std()])

49. 找到每行最大值索引

In [ ]:
a = np.arange(12).reshape(4, 3)
a.argmax(axis=1)

50. 将 1-D 数组变为列向量

In [36]:
a = np.arange(5).reshape(-1)
col = a[:, None]
col

array([[0],
       [1],
       [2],
       [3],
       [4]])