In [2]:
import numpy as np

1. 创建 1×5 全 0 浮点向量

In [7]:
a = np.zeros(5, dtype=float)
a

array([0., 0., 0., 0., 0.])

2. 创建 3×3 单位阵(对角线为1)

In [8]:
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

3. 生成 0–9 的数组  

In [10]:
my_list = range(0, 10)
my_list

range(0, 10)

4. 从 0 到 1 等间隔 5 个数  

In [12]:
my_list = np.linspace(0,1,5)
my_list

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

5. 随机 2×3 正态分布  

In [14]:
a = np.random.randn(2, 3)
a

array([[-0.62122007,  0.5105913 , -0.1832004 ],
       [-0.38875061, -0.86727411, -1.1598184 ]])

6. 将 1~6 变成 2×3 数组  

In [15]:
a = np.arange(1, 7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

7. 获取第 2 行整行  

In [19]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a = a[1, :]
a

array([4, 5, 6])

8. 获取第 1 列整列  

In [20]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a = a[:, 0]
a

array([1, 4])

9. 取前两行、后两列  

In [21]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a = a[:2, -2:]
a

array([[2, 3],
       [5, 6]])

10. 倒序整个数组

In [3]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a = a[::-1, ::-1]
a

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

11. 行倒序，列不变

In [4]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a = a[::-1, :]
a

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

12. 把 3×4 数组展平成一维

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [17, 18, 19]])
a = a.reshape(1,12)
a

# 此时a变成了只有一行数据的二维向量，不满足题意

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 17, 18, 19]])

In [ ]:
#可以做如下修改
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [17, 18, 19]])
x = b.ravel()      # 推荐，返回视图
y = b.flatten()    # 返回拷贝
z = b.reshape(-1)  # 显式变成一维